ScalablyTyped/Converter

build.sbt
sbt-converter06/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedConverterExternalNpmPlugin.scala
sbt-converter06/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedConverterPlugin.scala

This is just [WIP] because I'm waiting for the new version of scalajs-bundler to be published.
Since https://github.com/scalacenter/scalajs-bundler/pull/324#event-3044771159 is already merged.
With the new version of scalajs-bundler, we use the solution from @gzm0 (https://github.com/ScalablyTyped/Demos/issues/21#issuecomment-587046901) for the ScalaJs versions 0.6 and 1.0 without having to support each version independently.
I published everything local and tested with the ScalablyTyped/Demos and it seems to work with ScalaJs 1.0.0

[WIP] FIX #113: NoSuchMethodError currentBinaryVersion For ScalaJs 1.0.0

---

importer/src/test/scala/org/scalablytyped/converter/internal/ts/parser/ImportExportParseTests.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/parser/TsParser.scala

This is an attempt at fixing the issue I just opened, #127. The typescript parser was expecting an identifier before the type parameter even though it doesn't to be always the case.
I'm not sure about the fix (`.?` + `getOrElse`), but all the tests are passing. Let me know (or close this PR) if this isn't the right way to fix it. It now imports correctly `@antv/g6` (and thus `@antv/util`) but I haven't tried using it in Scala yet.

Fix ts parsing error on export default class <T>

---

importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/LibraryResolver.scala

On Windows, this removes the drive name, which causes a reconstruction of `os.Path` to fail.

Fix issue with usage of `segments` on an absolute `os.Path`

---

sbt-converter06/src/main/scala/org/scalablytyped/converter/internal/ZincCompiler.scala

As discussed on gitter.
The solution worked on a node connected to maven central,
and it worked on a node, only connected to an internal repository.

Use global resolvers when resolving the ZincCompiler

---

sbt-converter/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedConverterExternalNpmPlugin.scala
sbt-converter/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedConverterPlugin.scala

fixes https://github.com/ScalablyTyped/Converter/issues/156
didn't see an easy way to unit test it so I just checked manually :o

use ivyPath for publishLocalFolder

---

sbt-converter/src/main/scala/org/scalablytyped/converter/internal/ZincCompiler.scala

To make the sbt plugin work with a private proxy all repository. I've tested this successfully with a private Nexus.

Use credentials from the build when resolving dependencies

---

scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/transforms/FakeLiterals.scala

(fixes https://github.com/ScalablyTyped/ScalaJsReactDemos/pull/8 )

Limit how many fake literal string creator methods we output 

---

importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/ConversionOptions.scala
importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/ScalaJsBundlerDepFile.scala
importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/documentation/Npmjs.scala
importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/jsonCodecs.scala
importer/src/main/scala/org/scalablytyped/converter/internal/importer/Summary.scala
importer/src/main/scala/org/scalablytyped/converter/internal/importer/build/BinTrayPublisher.scala
importer/src/test/scala/org/scalablytyped/converter/internal/importer/JsonTests.scala
importer/src/test/scala/org/scalablytyped/converter/internal/importer/ScalaJsBundlerDepTest.scala
project/Deps.scala
sbt-converter/src/main/scala/org/scalablytyped/converter/internal/ImportTypings.scala
sbt-converter/src/main/scala/org/scalablytyped/converter/internal/ImportTypingsGenSources.scala
sbt-converter/src/main/scala/org/scalablytyped/converter/internal/RunCacheKey.scala
scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/Dep.scala
scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/SlinkyTagsLoader.scala
utils/src/main/scala/org/scalablytyped/converter/internal/Json.scala

Ok, so this PR is good news and bad news.
The good news is that this will enable publication to maven central (partially solving #262  ).
For the bad news, it'll break builds. Let's start with some background:
Circe is an amazing json library, and it's used in this sbt plugin and many others. However, it's not binary compatible across versions, and earlier on it caused a lot of friction where adding the ST plugin to a build would break other plugins (using an older version of circe). Before I fixed it, binary incompatibility with older versions of circe was the number one issue with the sbt plugin.
My fix was to manually shade all the circe modules, see https://github.com/ScalablyTyped/circe and https://github.com/ScalablyTyped/circe-jackson . All these modules were published to Bintray …

Drop manually shaded version of circe

---

sbt-converter/src/main/scala/org/scalablytyped/converter/internal/ImportTypingsGenSources.scala
scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/Minimization.scala
scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/transforms/Mangler.scala
utils/src/main/scala/org/scalablytyped/converter/internal/IArray.scala

- make `Minimization.Related` work like advertised, so it's also considered when including parent trees
- add a `Minimization.Related` tag to the `To`, `_to` and `^` members so it works with the new encoding

New implementation of Minimization (fixes #270)

---

importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/ImportType.scala
importer/src/test/scala/org/scalablytyped/converter/internal/ts/parser/ParserTests.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/TreeTransformation.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/TsTypeFormatter.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/parser/TsParser.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/transforms/ResolveTypeLookups.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/trees.scala

This PR adds support for labeled tuple elements that were [introduced](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#labeled-tuple-elements
) in Typescript 4.0 and further [enhanced](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html#leadingmiddle-rest-elements-in-tuple-types) in 4.2. I first encountered them in [react-map-gl](https://github.com/visgl/react-map-gl/blob/db08714945b106062a9e8b87722a8c0e343eb3de/src/components/interactive-map.d.ts#L12).
The label is not used for anything when producing Scala code but I decided not to ignore it and parse it and so I introduced `TsTupleElement` in place of bare `TsType`.
Many of the demo set tests succeeded but then entire run failed with an error that doesn't seem to be related to my changes. …

Add support for labeled tuple elements

---

sbt-converter/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedConverterGenSourcePlugin.scala

This is convenient when you don't want downstreams to inherit the dependency to the type definitions. In fact, I would expect this is the case for nearly all facades.

Include `npmDevDependencies` in `wantedLibs`

---

importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/Phase1ReadTypescript.scala
importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/Phase1Res.scala
importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/Phase2ToScalaJs.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/transforms/AddComments.scala

May want to output this is annotations or something which can be queried at build-time, perhaps we can even determine which polyfills are needed.
This is an example diff from the Javascript `String` type:
```diff
Index: s/std/src/main/scala/typings/std/String.scala
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/s/std/src/main/scala/typings/std/String.scala b/s/std/src/main/scala/typings/std/String.scala
--- a/s/std/src/main/scala/typings/std/String.scala	(revision 8c5a423807f78facc80b5f7a8b05871bae377d40)
+++ b/s/std/src/main/scala/typings/std/String.scala	(date 1630492245197)
@@ -18,33 +18,40 @@
@js.native
trait String
extends StObject
-     with /* index */ …
```

Note which standard all members in std are from

---

importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/ImportType.scala

I finally tested your suggestion. It works as expected (to not get that compilation error at code generation time https://github.com/ScalablyTyped/Converter/issues/438)
@oyvindberg Thank you. 
Would be great to have this included in the next release!

Fix #438: Instantiable23 type not found

---

importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/Source.scala
importer/src/main/scala/org/scalablytyped/converter/internal/importer/Ci.scala
importer/src/main/scala/org/scalablytyped/converter/internal/importer/UpToDateExternals.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/metadata.scala

there has been some bitrot in the CI tool, since no current version of npm can install all the packages it needs. it is also intensely slow and prone to crashes. it's also hard to make it always choose the newest packages.
- delay parsing some bits of package json until later. also make it more flexible
this replacement always pull the latest.

ci: replace npm with homegrown

---

importer/src/test/scala/org/scalablytyped/converter/internal/importer/ImporterTest.scala
tests/pixi.js/check-3/e/eventemitter3/build.sbt
tests/pixi.js/check-3/e/eventemitter3/project/build.properties
tests/pixi.js/check-3/e/eventemitter3/project/plugins.sbt
tests/pixi.js/check-3/e/eventemitter3/readme.md
tests/pixi.js/check-3/e/eventemitter3/src/main/scala/typings/eventemitter3/eventemitter3Require.scala
tests/pixi.js/check-3/e/eventemitter3/src/main/scala/typings/eventemitter3/mod.scala
tests/pixi.js/check-3/p/pixi__utils/build.sbt
tests/pixi.js/check-3/p/pixi__utils/project/build.properties
tests/pixi.js/check-3/p/pixi__utils/project/plugins.sbt
tests/pixi.js/check-3/p/pixi__utils/readme.md
tests/pixi.js/check-3/p/pixi__utils/src/main/scala/typings/pixiUtils/mod.scala
tests/pixi.js/check-3/p/pixi__utils/src/main/scala/typings/pixiUtils/pixiUtilsRequire.scala
tests/pixi.js/check-3/p/pixi_dot_js/build.sbt
tests/pixi.js/check-3/p/pixi_dot_js/project/build.properties
tests/pixi.js/check-3/p/pixi_dot_js/project/plugins.sbt
tests/pixi.js/check-3/p/pixi_dot_js/readme.md
tests/pixi.js/check-3/p/pixi_dot_js/src/main/scala/typings/pixiJs/mod.scala
tests/pixi.js/check-3/p/pixi_dot_js/src/main/scala/typings/pixiJs/pixiJsRequire.scala
tests/pixi.js/in/@pixi/utils/index.d.ts
tests/pixi.js/in/eventemitter3/index.d.ts
tests/pixi.js/in/pixi.js/index.d.ts
ts/src/main/scala/org/scalablytyped/converter/internal/ts/modules/DeriveCopy.scala

test case concerning this issue: https://github.com/ScalablyTyped/Converter/issues/471

Add minimized pixi.js test case

---

.run/CI Demoset.run.xml
importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/LibraryResolver.scala
importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/Phase1ReadTypescript.scala
importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/ProxyModule.scala
importer/src/test/scala/org/scalablytyped/converter/internal/importer/ExportsJsonTest.scala
tests/pixi.js/check-3/p/pixi_dot_js/build.sbt
tests/pixi.js/check-3/p/pixi_dot_js/src/main/scala/typings/pixiJs/mod.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/metadata.scala

- Dependent upon #366 
Solves the problem by injecting fake modules into the AST with `export import from '...'` taken from `exports` in `package.json`
The predictable module names will be split out into a separate PR

Add support for `exports`

---

tests/react-integration-test/check-japgolly-3/c/componentstest/build.sbt
tests/react-integration-test/check-japgolly-3/r/react-bootstrap/build.sbt
tests/react-integration-test/check-japgolly-3/r/react-contextmenu/build.sbt
tests/react-integration-test/check-japgolly-3/r/react-dropzone/build.sbt
tests/react-integration-test/check-japgolly-3/r/react-markdown/build.sbt
tests/react-integration-test/check-japgolly-3/r/react-select/build.sbt
tests/react-integration-test/check-japgolly-3/r/react/build.sbt
tests/react-integration-test/check-japgolly-3/r/react/src/main/scala/typingsJapgolly/react/anon.scala
tests/react-integration-test/check-japgolly-3/r/react/src/main/scala/typingsJapgolly/react/mod/package.scala
tests/react-integration-test/check-japgolly-3/s/semantic-ui-react/build.sbt
tests/react-integration-test/check-japgolly-3/s/stardust-ui__react-component-event-listener/build.sbt
tests/react-integration-test/check-japgolly-3/s/stardust-ui__react-component-ref/build.sbt
tests/react-integration-test/check-slinky-3/c/componentstest/build.sbt
tests/react-integration-test/check-slinky-3/r/react-bootstrap/build.sbt
tests/react-integration-test/check-slinky-3/r/react-contextmenu/build.sbt
tests/react-integration-test/check-slinky-3/r/react-dropzone/build.sbt
tests/react-integration-test/check-slinky-3/r/react-markdown/build.sbt
tests/react-integration-test/check-slinky-3/r/react-select/build.sbt
tests/react-integration-test/check-slinky-3/r/react/build.sbt
tests/react-integration-test/check-slinky-3/r/react/src/main/scala/typingsSlinky/react/anon.scala
tests/react-integration-test/check-slinky-3/r/react/src/main/scala/typingsSlinky/react/mod/package.scala
tests/react-integration-test/check-slinky-3/s/semantic-ui-react/build.sbt
tests/react-integration-test/check-slinky-3/s/stardust-ui__react-component-event-listener/build.sbt
tests/react-integration-test/check-slinky-3/s/stardust-ui__react-component-ref/build.sbt
ts/src/main/scala/org/scalablytyped/converter/internal/ts/modules/Exports.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/modules/ReplaceExports.scala

- improve shadowing logic to not combine re-exported `default` exports from multiple modules.
- note: changes ordering post-module resolution, so anon names will change

modules: named exports can also export default

---

importer/src/test/resources/parsertests/trailing-commas.d.ts
importer/src/test/scala/org/scalablytyped/converter/internal/ts/parser/ParserTests.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/parser/TsParser.scala

Please review the pull request. This fixes sbt-converter with vaadin library v23.1+.

Implement support for trailing commas in function calls

---

project/build.properties
sbt-converter/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedPluginBase.scala
sbt-converter/src/sbt-test/react/external/project/build.properties

- Upgrade to sbt 1.9.0
- Fixed the version check to support sbt 1.8.0 or later
- Use sbt 1.9.0 in one of the sbt scripted test projects to check the behavior

Fixes #539: Support sbt 1.9.0 projects

---

cli/src/main/scala/org/scalablytyped/converter/cli/Main.scala

add `org.scalablytyped.converter.cli.Converter.mainNoExit()` method allowing to embed the CLI tool into other software, when terminating of JVM at the end of the conversion is not desirable

add `org.scalablytyped.converter.cli.Converter.mainNoExit()` method

---

sbt-converter/src/main/scala/org/scalablytyped/converter/internal/ScalaJsBundlerHack.scala

Append Typescript to npmDevDependencies instead of npmDependencies.

---

docs/devel/about.md
importer/src/test/scala/org/scalablytyped/converter/internal/ts/parser/ImportExportParseTests.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/parser/TsParser.scala

Support export all types

---

build.sbt

This causes the BSP import in IntelliJ to fail with no meaningful message. See https://youtrack.jetbrains.com/issue/SCL-20474/Unable-to-import-BSP-project.

Do not disable BSP

---

scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/SlinkyTypeConversions.scala
tests/react-integration-test/check-japgolly-3/c/componentstest/build.sbt
tests/react-integration-test/check-japgolly-3/c/componentstest/src/main/scala/typingsJapgolly/componentstest/mod.scala
tests/react-integration-test/check-slinky-3/c/componentstest/build.sbt
tests/react-integration-test/check-slinky-3/c/componentstest/src/main/scala/typingsSlinky/componentstest/mod.scala
tests/react-integration-test/check-slinky-3/r/react-bootstrap/build.sbt
tests/react-integration-test/check-slinky-3/r/react-bootstrap/src/main/scala/typingsSlinky/reactBootstrap/components/ButtonGroup.scala
tests/react-integration-test/check-slinky-3/r/react-bootstrap/src/main/scala/typingsSlinky/reactBootstrap/components/ToggleButtonGroup.scala
tests/react-integration-test/check-slinky-3/r/react-contextmenu/build.sbt
tests/react-integration-test/check-slinky-3/r/react-dropzone/build.sbt
tests/react-integration-test/check-slinky-3/r/react-markdown/build.sbt
tests/react-integration-test/check-slinky-3/r/react-select/build.sbt
tests/react-integration-test/check-slinky-3/r/react/build.sbt
tests/react-integration-test/check-slinky-3/r/react/src/main/scala/typingsSlinky/react/components/SharedBuilder_DetailedHTMLProps_1670340210.scala
tests/react-integration-test/check-slinky-3/r/react/src/main/scala/typingsSlinky/react/components/a.scala
tests/react-integration-test/check-slinky-3/r/react/src/main/scala/typingsSlinky/react/components/area.scala
tests/react-integration-test/check-slinky-3/r/react/src/main/scala/typingsSlinky/react/components/audio.scala
tests/react-integration-test/check-slinky-3/r/react/src/main/scala/typingsSlinky/react/components/base.scala
tests/react-integration-test/check-slinky-3/r/react/src/main/scala/typingsSlinky/react/components/view.scala
tests/react-integration-test/check-slinky-3/r/react/src/main/scala/typingsSlinky/react/mod/DOMAttributes.scala
tests/react-integration-test/check-slinky-3/r/react/src/main/scala/typingsSlinky/react/mod/package.scala
tests/react-integration-test/check-slinky-3/s/semantic-ui-react/build.sbt
tests/react-integration-test/check-slinky-3/s/semantic-ui-react/src/main/scala/typingsSlinky/semanticUiReact/components/Button.scala
tests/react-integration-test/check-slinky-3/s/semantic-ui-react/src/main/scala/typingsSlinky/semanticUiReact/components/Input.scala
tests/react-integration-test/check-slinky-3/s/stardust-ui__react-component-event-listener/build.sbt
tests/react-integration-test/check-slinky-3/s/stardust-ui__react-component-ref/build.sbt
tests/react-integration-test/in/componentstest/index.d.ts

This fixes the bug in #596 where Slinky SyntheticEvent type parameters are around the wrong way.

Fix ordering of Slinky SyntheticEvent type parameters

---

.github/workflows/release-snapshot.yml

Changed the workflow trigger from push to workflow_dispatch, so snapshots will only be published when manually triggered. This can be re-enabled later when needed.

Disable automatic snapshot publishing

---

.github/workflows/ci-build.yml
.github/workflows/release-snapshot.yml

Update all GitHub Actions to their latest versions, upgrade JVM from Java 11 to Java 21, and fix deprecation warnings that appear in CI logs.
- **JVM**: `adopt:11` → `adoptium:1.21.0.1` (Java 11 → Java 21)
- Fixes JVM installation failure: "JVM adopt:11 not found in index"
- Upgrades to modern LTS Java version for better performance
- **actions/checkout**: `v2`/`v3` → `v4`
- **actions/cache**: `v3` → `v4`  
- **coursier/setup-action**: `v1.2.0-M3` → `v1`
- **coursier/cache-action**: `v6` → `v6.4`
- Replace deprecated `::set-output` command with `$GITHUB_OUTPUT` environment file
- Before: `echo "::set-output name=sha::$(git ls-tree HEAD tests --object-only)"`
- After: `echo "sha=$(git ls-tree HEAD tests --object-only)" >> $GITHUB_OUTPUT`
- **Fixes CI build failures** caused by missing JVM …

ci: Update GitHub Actions and JVM to latest versions

---

importer/src/test/scala/org/scalablytyped/converter/internal/ts/parser/ParserTests.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/parser/TsParser.scala

Multiple critical TypeScript parser fixes that improve handling of advanced type patterns, destructured parameters, and parser robustness.
**Problem:** Parser failed on parenthesized types followed by array index access:
- `(T & U)[K]`
- `(Partial<T>)[keyof T]`
**Solution:** Reordered parser alternatives to handle parenthesized expressions correctly.
**Problem:** Multiple issues with destructured parameters and mapped types:
- Destructured parameters weren't generating proper unique names
- Rest properties in destructured objects weren't handled
- Mapped types with `in keyof` syntax failed
**Solution:**
- Improved destructured parameter parsing for rest properties (`...rest`)
- Fixed unique name generation (using `param0`, `param1`, etc.)
- Enhanced mapped type parsing for `in keyof` …

fix: Comprehensive TypeScript parser improvements

---

tests/react-integration-test/check-japgolly-3/s/semantic-ui-react/build.sbt
tests/react-integration-test/check-japgolly-3/s/semantic-ui-react/src/main/scala/typingsJapgolly/semanticUiReact/distCommonjsElementsButtonButtonMod.scala
tests/react-integration-test/check-japgolly-3/s/semantic-ui-react/src/main/scala/typingsJapgolly/semanticUiReact/distCommonjsElementsButtonMod.scala
tests/react-integration-test/check-slinky-3/s/semantic-ui-react/build.sbt
tests/react-integration-test/check-slinky-3/s/semantic-ui-react/src/main/scala/typingsSlinky/semanticUiReact/distCommonjsElementsButtonButtonMod.scala
tests/react-integration-test/check-slinky-3/s/semantic-ui-react/src/main/scala/typingsSlinky/semanticUiReact/distCommonjsElementsButtonMod.scala
tests/sax/check-3/n/node/build.sbt
tests/sax/check-3/n/node/src/main/scala/typings/node/bufferMod.scala
tests/sax/check-3/s/sax/build.sbt
tests/tstl/check-3/t/tstl/build.sbt
tests/tstl/check-3/t/tstl/src/main/scala/typings/tstl/global.scala
tests/tstl/check-3/t/tstl/src/main/scala/typings/tstl/std.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/transforms/PreferTypeAlias.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/transforms/ResolveTypeQueries.scala

Fix potential hang in type query resolution by limiting the depth of resolution to prevent infinite recursion.
The type query resolution mechanism (`typeof` expressions) could enter infinite loops when:
- Circular type references exist
- Deep nested type queries are resolved recursively
- Complex type hierarchies cause unbounded resolution attempts
This would cause the converter to hang indefinitely on certain TypeScript definition files.
Made type query resolution less aggressive by:
- Limiting the depth of recursive resolution
- Adding safeguards against circular references
- Simplifying resolution for deeply nested queries
- Trading some precision for guaranteed termination
The fix modifies type query resolution logic across multiple files to:
1. Track resolution depth
2. Bail out …

fix: Prevent hang in type query resolution

---

core/src/main/scala/org/scalablytyped/converter/internal/ts/TsTypeFormatter.scala
core/src/main/scala/org/scalablytyped/converter/internal/ts/trees.scala
importer/src/test/scala/org/scalablytyped/converter/internal/ts/parser/CommentTests.scala
importer/src/test/scala/org/scalablytyped/converter/internal/ts/parser/ImportExportParseTests.scala
importer/src/test/scala/org/scalablytyped/converter/internal/ts/parser/ParserTests.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/FillInTParams.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/TreeTransformation.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/parser/TsLexer.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/parser/TsParser.scala
ts/src/main/scala/org/scalablytyped/converter/internal/ts/transforms/ExpandTypeParams.scala

Add support for TypeScript 4.7+ variance annotations (`in` and `out` keywords) for type parameters.
TypeScript 4.7 introduced explicit variance annotations that allow developers to specify:
- **`out`** (covariant): Type parameter only appears in output positions
- **`in`** (contravariant): Type parameter only appears in input positions
- **No annotation** (invariant): Default behavior
These annotations help TypeScript provide better type checking and enable more precise type relationships.
```scala
sealed trait Variance
object Variance {
case object Invariant extends Variance
case object Covariant extends Variance     // out
case object Contravariant extends Variance  // in
}
```
```scala
final case class TsTypeParam(
comments:   Comments,
name:       TsIdentSimple,
upperBound: …
```

feat: Add support for TypeScript variance annotations
